### ISSUE TITLE
Contacting

### ISSUE THREAD

**Issue by RobloxArchiver** [Thing34872/minecraft-texture-pack#2]
Hello Thing34872,

I'd be interested in getting in contact with you. Please feel free to shoot me an email if you'd like to get in contact. 

Sincerely, 
RobloxArchiver

**Comment by Thing34872** [comment]
> Hello Thing34872,
> 
> I'd be interested in getting in contact with you. Please feel free to shoot me an email if you'd like to get in contact.
> 
> Sincerely, RobloxArchiver

I am sorry, but I am working on an app, maybe next month?
My email is thing3487@gmail.com
